### PR TITLE
bugfix: allow bond as NIC

### PR DESCRIPTION
**Pull request by chifu1234**

### CODE REVIEW

**Comment by yaocw2020** [comment]
https://github.com/harvester/harvester/issues/984
 It has been solved.

**Comment by chifu1234** [comment]
Ok I just tested it with the version on branch main and it did not work. For me it seems that getNICFromStatus does the filtering.

**Comment by yaocw2020** [comment]
> Ok I just tested it with the version on branch main and it did not work. For me it seems that getNICFromStatus does the filtering.

Did you select the NIC from UI? The UI need some modification because I change the API.

**Comment by chifu1234** [comment]
ez will try this week thxs!

**Comment by yaocw2020** [comment]
https://github.com/harvester/harvester/issues/980
The related issue.

**Comment by chifu1234** [comment]
ez will try this week thxs!

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/network-controller-harvester/pull/37, feel free to re-open it if u encounter any related issues, thanks

**Pull request closed without merging**
