### PR TITLE
Bump dhcp client package

### PR DESCRIPTION
**Pull request by w13915984028**
**Problem:**

The vendor github.com/insomniacslk/dhcp was old

**Solution:**

Bump to latest

**Related Issue:**
Partially related to https://github.com/harvester/harvester/issues/3428

**Test plan:**

1. create VM network
2. dhcp detect should be successful

### CODE REVIEW

**Review by starbops — APPROVED** [review]
Tested with newly created VM Networks. LGTM, thank you.

**Review by mingshuoqiu — APPROVED** [review]
Tested w/o problem. Thanks

**Comment by starbops** [comment]
@w13915984028 since it's a bug fix, do we want to backport it to v0.4.x (corresponds to Harvester v1.3). And we've cut another branch v0.5.x for Harvester v1.4 release, we need to backport this to v0.5.x branch, too.

cc @mingshuoqiu

**Comment by w13915984028** [comment]
@starbops I did not notice there are also branchs here. 
Backport v0.5.x is required, for v0.4.x we can also give it a try. thanks.

**Comment by w13915984028** [comment]
@mergify backport v0.4.x v0.5.x

**Pull request merged**
