### PR TITLE
Add validation for max length of cluster network name

### PR DESCRIPTION
**Pull request by rrajendran17**
**Problem:**
when creating a cluster network using GUI, user specifies a name for cluster network and it is validated for maximum length of 12 at the UI code,but when cluster network with name > 12 chars is created using API, the cluster network is created successfully.

cluster network webhook validator is missing the max length check for cluster network name.
Later it is validated when vlan config is applied on the same cluster network.
But the creation of cluster network should validate it.

**Solution:**
Added create function in cluster network validator to validate for maximum length of cluster network name.

**Related Issue:**

harvester/harvester#3826

**Test plan:**
Manually tested on a harvester node with the changes.

### CODE REVIEW

**Review by starbops — APPROVED** [review]
LGTM, thank you!

**Review by mingshuoqiu — APPROVED** [review]
LGTM. Thank you.

**Comment by lanfon72** [comment]
@bk201 does this need backport to old versions?

**Comment by bk201** [comment]
yes, we need a backport. I [updated some comments about the workflow ](https://github.com/harvester/harvester/issues/3826#issuecomment-2288070407)and I moved the issue back to review first because the change didn't land in v1.4-head either.

**Pull request merged**
