### PR TITLE
must judge whether nodesFilter is empty

### PR DESCRIPTION
**Pull request by yaocw2020**
Related issue: https://github.com/harvester/harvester/issues/3579

### CODE REVIEW

**Review by guangbochen — COMMENTED** [review]
I can't reproduce the issues per https://github.com/harvester/harvester/issues/3579#issue-1606442300, can you please help to add the related logs and analysis, thanks.

**Comment by yaocw2020** [comment]
> I can't reproduce the issues per [harvester/harvester#3579 (comment)](https://github.com/harvester/harvester/issues/3579#issue-1606442300), can you please help to add the related logs and analysis, thanks.

https://github.com/harvester/harvester/issues/3579#issuecomment-1452176625

**Review by chrisho — APPROVED** [review]
LGTM and verified work fine, thanks.
image
image

**Review by guangbochen — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
